---
title: "Liana_NK-Plasma"
author: "Jacopo Umberto Verga"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Cell cell interactions with liana

```{r}
library(Seurat)
library(tidyverse)
library(magrittr)
library(liana)
library(BiocParallel)
```

Data:

```{r}
dat <- readRDS("Data/nk_plasma_mm.Rds")
dat
table(dat$new_label)
```

```{r}
dat <- SetIdent(dat, value="new_label")
dat <- NormalizeData(dat)
```
```{r}
multicoreParam <- MulticoreParam(workers = 10)
```

```{r}
test_liana <- liana_wrap(dat, BPPARAM = multicoreParam)
```
```{r}
test_liana <- test_liana %>%
  liana_aggregate()
```
```{r fig.height=10, fig.width=10}
test_liana %>%
  liana_dotplot(source_groups = c("Plasma"),
                target_groups = c("NK exhausted"),
                ntop = 20)
```
```{r fig.height=10, fig.width=10}
test_liana %>%
  liana_dotplot(source_groups = c("NK exhausted"),
                target_groups = c("Plasma"),
                ntop = 20)
```
```{r fig.height=10, fig.width=10}
test_liana %>%
  liana_dotplot(source_groups = c("NK exhausted"),
                target_groups = c("NK exhausted"),
                ntop = 20)
```

```{r}
liana_trunc <- test_liana %>%
   # only keep interactions concordant between methods
  filter(aggregate_rank <= 0.1) # note that these pvals are already corrected

heat_freq(liana_trunc)
```
```{r}
p <- chord_freq(liana_trunc,
                source_groups = c("NK exhausted","Plasma"),
                target_groups = c("NK exhausted","Plasma"))
```

```{r}
write.csv(liana_trunc, "NK_plasma_interactions.csv")
```

