---
title: "SCENIC mm"
author: "Jacopo Umberto Verga"
format: html
editor: visual
---

# SCENIC on mm NK cells:

Let's prepare the environment

```{r}
library(SCENIC)

library(AUCell)

library(RcisTarget)

library(SingleCellExperiment)

library(Seurat)

library(dplyr)
```

the motif databases for humans:

```{r}
dbFiles <- c("https://resources.aertslab.org/cistarget/databases/old/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/hg19-500bp-upstream-7species.mc9nr.feather",
"https://resources.aertslab.org/cistarget/databases/old/homo_sapiens/hg19/refseq_r45/mc9nr/gene_based/hg19-tss-centered-10kb-7species.mc9nr.feather")

dir.create("cisTarget_databases")
setwd("cisTarget_databases")

for(featherURL in dbFiles)
{
  download.file(featherURL, destfile=basename(featherURL)) # saved in current dir
}
setwd("..")
```

and load the data:

```{r}
dat <- readRDS("Data/mm_nk.Rds")
dat <- as.SingleCellExperiment(dat)
dat

exprMat <- counts(dat)
cellInfo <- colData(dat)
```

## Initialise scenic

```{r}
scenicOptions <- initializeScenic(org="hgnc", dbDir=("cisTarget_databases"), nCores=6)
saveRDS(scenicOptions, file="Data/scenicOptions.Rds") 
```
